version: "3.8"

services:
  aspnet-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
      - "8001:8001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8000
      - DOTNET_USE_POLLING_FILE_WATCHER=true
      - DOTNET_RUNNING_IN_CONTAINER=true
    volumes:
      - .:/workspace:cached
      - aspnet-dev-nuget:/home/vscode/.nuget
      - aspnet-dev-vscode:/home/vscode/.vscode-server
    command: sleep infinity
    networks:
      - aspnet-dev-network

  mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mos
      MYSQL_USER: mos
      MYSQL_PASSWORD: mos
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./database/init:/docker-entrypoint-initdb.d
    networks:
      - aspnet-dev-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
      interval: 10s

volumes:
  aspnet-dev-nuget:
  aspnet-dev-vscode:

networks:
  aspnet-dev-network:
    driver: bridge
