<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Product;
use App\Models\Category;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */


    public function run(): void
    {
        // カテゴリの最大値からランダムidを取得
        function fake_category_id() {
            $maxId = Category::max('id');
            return rand(1, $maxId);
        }

        $products = [
            [
                'id' => 1,
                'slug' => 'burger1',
                'name' => 'モスバーガー',
                'description' => '',
                'image' => 'burger1.jpg',
                'price' => 440.00,
                'sortid' => 1,
                'display' => true,
                'category_id' => fake_category_id(),
            ],
            [
                'id' => 2,
                'slug' => 'burger2',
                'name' => 'モスチーズバーガー',
                'description' => '',
                'image' => 'burger2.jpg',
                'price' => 480.00,
                'sortid' => 2,
                'display' => true,
                'category_id' => fake_category_id(),
            ],
            [
                'id' => 3,
                'slug' => 'burger3',
                'name' => 'ダブルモスバーガー',
                'description' => '',
                'image' => 'burger3.jpg',
                'price' => 600.00,
                'sortid' => 3,
                'display' => true,
                'category_id' => fake_category_id(),
            ],
            [
                'id' => 4,
                'slug' => 'burger4',
                'name' => 'ダブルモスチーズバーガー',
                'description' => '',
                'image' => 'burger4.jpg',
                'price' => 640.00,
                'sortid' => 4,
                'display' => true,
                'category_id' => fake_category_id(),
            ],
            [
                'id' => 5,
                'slug' => 'burger5',
                'name' => 'スパイシーモスバーガー',
                'description' => '',
                'image' => 'burger5.jpg',
                'price' => 480.00,
                'sortid' => 5,
                'display' => true,
                'category_id' => fake_category_id(),
            ],
            [
                'id' => 6,
                'slug' => 'burger6',
                'name' => 'スパイシーモスチーズバーガー',
                'description' => '',
                'image' => 'burger6.jpg',
                'price' => 520.00,
                'sortid' => 6,
                'display' => true,
                'category_id' => fake_category_id(),
            ],
            [
                'id' => 7,
                'slug' => 'burger7',
                'name' => 'スパイシーダブルモスバーガー',
                'description' => '',
                'image' => 'burger7.jpg',
                'price' => 640.00,
                'sortid' => 7,
                'display' => true,
                'category_id' => fake_category_id(),
            ],
            [
                'id' => 8,
                'slug' => 'burger8',
                'name' => 'スパイシーダブルモスチーズバーガー',
                'description' => '',
                'image' => 'burger8.jpg',
                'price' => 640.00,
                'sortid' => 8,
                'display' => true,
                'category_id' => fake_category_id(),
            ],
            [
                'id' => 9,
                'slug' => 'burger9',
                'name' => 'テリヤキバーガー',
                'description' => '',
                'image' => 'burger9.jpg',
                'price' => 430.00,
                'sortid' => 9,
                'display' => true,
                'category_id' => fake_category_id(),
            ],
            [
                'id' => 10,
                'slug' => 'burger10',
                'name' => 'モス野菜バーガー',
                'description' => '',
                'image' => 'burger10.jpg',
                'price' => 440.00,
                'sortid' => 10,
                'display' => true,
                'category_id' => fake_category_id(),
            ],
            [
                'id' => 11,
                'slug' => 'hotdog1',
                'name' => 'ホットドッグ',
                'description' => '',
                'image' => 'hotdog1.jpg',
                'price' => 400.00,
                'sortid' => 11,
                'display' => true,
                'category_id' => fake_category_id(),
            ],
            [
                'id' => 12,
                'slug' => 'hotdog2',
                'name' => 'チリドッグ',
                'description' => '',
                'image' => 'hotdog2.jpg',
                'price' => 430.00,
                'sortid' => 12,
                'display' => true,
                'category_id' => fake_category_id(),
            ],
            [
                'id' => 13,
                'slug' => 'hotdog3',
                'name' => 'スパイシーチリドッグ',
                'description' => '',
                'image' => 'hotdog3.jpg',
                'price' => 470.00,
                'sortid' => 13,
                'display' => true,
                'category_id' => fake_category_id(),
            ],
            [
                'id' => 14,
                'slug' => 'soiburger1',
                'name' => 'ソイモスバーガー',
                'description' => '',
                'image' => 'soiburger1.jpg',
                'price' => 460.00,
                'sortid' => 14,
                'display' => true,
                'category_id' => fake_category_id(),
            ],
            [
                'id' => 15,
                'slug' => 'soiburger2',
                'name' => 'ソイバーガー',
                'description' => '',
                'image' => 'soiburger2.jpg',
                'price' => 260.00,
                'sortid' => 15,
                'display' => true,
                'category_id' => fake_category_id(),
            ],
            [
                'id' => 16,
                'slug' => 'soiburger3',
                'name' => 'ソイチーズバーガー',
                'description' => '',
                'image' => 'soiburger3.jpg',
                'price' => 300.00,
                'sortid' => 16,
                'display' => true,
                'category_id' => fake_category_id(),
            ],
            [
                'id' => 17,
                'slug' => 'side1',
                'name' => 'フレンチフライポテト',
                'description' => '',
                'image' => 'side1.jpg',
                'price' => 240.00,
                'sortid' => 17,
                'display' => true,
                'category_id' => fake_category_id(),
            ],
            [
                'id' => 18,
                'slug' => 'side2',
                'name' => 'オニポテ（フレンチフライポテト＆オニオンフライ）',
                'description' => '',
                'image' => 'side2.jpg',
                'price' => 300.00,
                'sortid' => 18,
                'display' => true,
                'category_id' => fake_category_id(),
            ],
            [
                'id' => 19,
                'slug' => 'side3',
                'name' => 'モスチキン',
                'description' => '',
                'image' => 'side3.jpg',
                'price' => 320.00,
                'sortid' => 19,
                'display' => true,
                'category_id' => fake_category_id(),
            ],
            [
                'id' => 20,
                'slug' => 'side4',
                'name' => 'チキンナゲット',
                'description' => '',
                'image' => 'side4.jpg',
                'price' => 360.00,
                'sortid' => 20,
                'display' => true,
                'category_id' => fake_category_id(),
            ],
            [
                'id' => 21,
                'slug' => 'drink1',
                'name' => 'アイスコーヒー',
                'description' => '',
                'image' => 'drink1.jpg',
                'price' => 260.00,
                'sortid' => 21,
                'display' => true,
                'category_id' => fake_category_id(),
            ],
            [
                'id' => 22,
                'slug' => 'drink2',
                'name' => 'アイスティ',
                'description' => '',
                'image' => 'drink2.jpg',
                'price' => 260.00,
                'sortid' => 22,
                'display' => true,
                'category_id' => fake_category_id(),
            ],
            [
                'id' => 23,
                'slug' => 'drink3',
                'name' => 'ブレンドコーヒー',
                'description' => '',
                'image' => 'drink3.jpg',
                'price' => 290.00,
                'sortid' => 23,
                'display' => true,
                'category_id' => fake_category_id(),
            ],
            [
                'id' => 24,
                'slug' => 'dessert1',
                'name' => 'ひんやりドルチェ 葛 ベリー',
                'description' => '',
                'image' => 'dessert1.jpg',
                'price' => 260.00,
                'sortid' => 24,
                'display' => true,
                'category_id' => fake_category_id(),
            ],
            [
                'id' => 25,
                'slug' => 'dessert2',
                'name' => 'ひんやりドルチェ 葛 トロピカル',
                'description' => '',
                'image' => 'dessert2.jpg',
                'price' => 260.00,
                'sortid' => 25,
                'display' => true,
                'category_id' => fake_category_id(),
            ],
        ];

        foreach ($products as $product) {
            Product::create($product);
        }
    }
}
